[[redirects]]
  from = "/items"
  to = "https://cart-app.netlify.com/items"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"